name = "japan-anime-shoten"
compatibility_date = "2024-04-05"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "japan-anime-shoten-db"
database_id = "11e1901c-f5e8-4879-80a6-8b2b784fb113"


